Added ability to specify a different server address for the tentacle comms
OctopusDeploy/OctopusTentacle pull request #440
Opened 2023-01-11 22:46 UTC by bradleyjford

# Background

> [We are adding polling tentacles over standard ports (443) to Octopus Cloud](https://docs.google.com/document/d/1iOigyxajs1rLbGGUZSwl9AR8HMJFkww5MSvZoiRU6eM/edit#heading=h.g165efrlab8g). For that, we need the polling tentacle to use a different server address for the web traffic and the tentacle traffic.

This PR supersedes the PoC [#414](https://github.com/OctopusDeploy/OctopusTentacle/pull/414) with updates to the Docker files and the addition of unit tests. 

We have introduced a new `--server-comms-address` CLI argument to the `register-worker` and `register-machine` commands.

# Results

Fixes https://github.com/OctopusDeploy/Issues/issues/... _(optional public issue)_

Fixes https://github.com/OctopusDeploy/ResearchAndDevelopment/issues/... _(optional private issue)_

See [How we use GitHub Issues](https://github.com/OctopusDeploy/Issues/blob/master/docs/CONTRIBUTING.internal.md) (including [this flowchart](https://whimsical.com/r-d-incoming-work-workflow-aug-21-NsDnGQXcwBLwU66a88Zhue) 

## Before

The same address was used for both the web and tentacle traffic.

## After

```
.\tentacle.exe register-worker  .... --server "https://pawel-stable3.testoctopus.app"  --server-comms-port "443" --server-comms-address "https://polling.pawel-stable3.testoctopus.app"
```

![image](https://user-images.githubusercontent.com/1689544/211927795-1a9e10ee-bd7f-4ac3-8f07-1b6c97b4bee9.png)

# How to review this PR

Quality :heavy_check_mark:

# Pre-requisites

- [ ] I have read [How we use GitHub Issues](https://github.com/OctopusDeploy/Issues/blob/master/docs/CONTRIBUTING.internal.md) for help deciding when and where it's appropriate to make an issue.
- [ ] I have considered informing or consulting the right people, according to the [ownership map](https://whimsical.com/ownership-map-NzbiD4HJyvhC9jNJNfS6TG).
- [ ] I have considered appropriate testing for my change.

2023-01-12 00:15 UTC, zentron requested changes
The individual changes look like they make sense.

I can see how providing the `server-comms-address` separate to the existing `server` argument allows you to use the `server` parameter for purely the registration invocation, leaving comms to go via another address. all good 👍 

Given though we use that `--server`  argument for other commands i'd like to make sure we are covering this behavioural addition in those places as well.
Should this argument also be added to the `PollCommand` as well?

2023-01-17 01:31 UTC, sahanocto commented
@zentron As requested, we have updated the `PollCommand` to accept the new `--server-comms-address` argument. We are happy for you to have another review. Thanks.

2023-01-17 02:28 UTC, zentron commented
Thanks for following up. Happy with the final merge

2023-01-17 04:04 UTC, zentron approved these changes
Approved

2023-01-17 04:45 UTC, merged