Sast/tentacle manager/proxy wizard
OctopusDeploy/OctopusTentacle pull request #798
Opened 2024-02-08 23:59 UTC by raynhamdev

# Background
We want to add some automated tests to Tentacle Manager as part of the [Tentacle Manager on .NET](https://app.shortcut.com/octopusdeploy/epic/68113/tentacle-manager-on-windows-net-core) project.

We first need to make the Tentacle Manager project testable by automated tests (e.g. NUnit) by separating the UI logic from the business logic. This will allow the automated tests to exercise most of the code (i.e. everything _not_ in a UI component) without the pain of dealing with UI threads and Dispatchers etc.

This PR refactors the `ProxyWizardModel` component in TentacleManager to separate its business logic from the view.

[sc-70325]

# Results

There should be *zero visible changes* from an end-user's perspective. The intent is that the functionality is completely unchanged, but the code base is in a better shape for automated tests.

Summary of the main changes within:
- `ProxyWizardModel` now derive from `ShellViewModel`
- `ProxyWizardLauncher` is now removed
   - `TentacleManagerModel` creates the `ProxyWizardModel`
   - `TentacleManagerView` creates the `ShellView` for `ProxyWizardModel`
- `ProxyWizardModel` and `PollingProxyWizardModel` are simplified by removing unnecessary constructor's params.

# How to review this PR

Quality :heavy_check_mark:

As there are no automated tests, the only way to verify this PR is to manually test the Tentacle Manager. There's not much functionality in here, so testing the following should cover everything:
* Install new instance
* Reinstall existing instance
* Restart service
* Start service
* Stop service
* Update proxy settings
* Delete instance

# Pre-requisites

- [x] I have read [How we use GitHub Issues](https://github.com/OctopusDeploy/Issues/blob/main/docs/CONTRIBUTING.internal.md) for help deciding when and where it's appropriate to make an issue.
- [x] I have considered informing or consulting the right people, according to the [ownership map](https://whimsical.com/ownership-map-NzbiD4HJyvhC9jNJNfS6TG).
- [x] I have considered appropriate testing for my change.

2024-02-09 02:37 UTC, acodrington requested changes
A few things I'm not sure about, we can 🍐 and discuss it further

2024-02-09 03:32 UTC, raynhamdev commented on source/Octopus.Manager.Tentacle/Proxy/ProxyWizardModelWrapper.cs
Based on my understanding, the wrapper is designed to contain either (a `ProxyWizardModel`) or (a `ProxyWizardModel` plus a `PollingProxyWizardModel`), depending on the proxy settings in `TentacleManagerModel`.
We still need it. However, I have moved the code related to the wrapper to `TentacleManagerModel`.

2024-02-12 05:53 UTC, acodrington commented on source/Octopus.Manager.Tentacle/Proxy/ProxyWizardModelWrapper.cs
Hmm... I think we can simplify this further, but it's not a priority. We've achieved our goal by separating the UI controls from the view model(s), so that will be enough for now - we can always revisit later if it becomes important, or for sharpening etc.

2024-02-12 05:53 UTC, acodrington approved these changes
👍🏻

2024-02-12 23:58 UTC, merged